[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/favicon.ico"
  to = "/static/favicon/favicon.ico"
  status = 301
  
# marketing redirects

[[redirects]]
  from = "https://www.courier.com/sedaily"
  to = "https://www.courier.com/?utm_medium=podcast&utm_source=sedaily&utm_campaign=se-daily-podcast-q1"
  status = 301
  force = true
  
# site redirects to keep everything on the same domain

[[redirects]]
  from = "http://courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://www.courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true

[[redirects]]
  from = "https://courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true

[[redirects]]
  from = "https://courier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "http://trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
