[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy-Report-Only = "object-src 'none'; default-src 'self' api-iam.intercom.io api.segment.io cdn.heapanalytics.com cdn.segment.io 
    fonts.googleapis.com fonts.gstatic.com forms.hubspot.com heapanalytics.com js-na1.hs-scripts.com js.hs-analytics.net js.hs-banner.com 
    js.hscollectedforms.net js.intercomcdn.com self track.hubspot.com widget.intercom.io www.google-analytics.com www.googletagmanager.com null 
    images.ctfassets.net wss://nexus-websocket-a.intercom.io api.hubapi.com connect.facebook.net js.hsadspixel.net 
    px.ads.linkedin.com snap.licdn.com www.facebook.com www.google.com www.google.dk downloads.intercomcdn.com messenger-apps.intercom.io 
    static.intercomassets.com www.google.co.in www.google.co.nz www.google.ca www.google.com.br www.google.com.do www.google.es www.youtube.com wss 
    www.google.fr www.google.hu www.google.lu www.linkedin.com; script-src 'self' cdn.segment.io js.intercomcdn.com widget.intercom.io cdn.heapanalytics.com 
    js-na1.hs-scripts.com js.hs-analytics.net js.hs-banner.com js.hscollectedforms.net www.google-analytics.com www.googletagmanager.com 
    connect.facebook.net js.hsadspixel.net snap.licdn.com; script-src-elem 'self' widget.intercom.io www.google-analytics.com www.googletagmanager.com 
    cdn.heapanalytics.com cdn.segment.io js-na1.hs-scripts.com js.hs-analytics.net js.hs-banner.com js.hscollectedforms.net js.intercomcdn.com 
    connect.facebook.net js.hsadspixel.net snap.licdn.com www.google.com; style-src 'self' fonts.googleapis.com; style-src-elem 'self' fonts.googleapis.com; 
    img-src 'self' data: www.google-analytics.com heapanalytics.com images.ctfassets.net track.hubspot.com js.intercomcdn.com static.intercomassets.com 
    i.ytimg.com px.ads.linkedin.com www.facebook.com www.google.ca www.google.com www.gstatic.com downloads.intercomcdn.com messenger-apps.intercom.io 
    p.adsymptotic.com www.google.co.jp www.google.co.kr www.google.co.uk www.google.de www.google.gr www.google.ro www.google.ru www.linkedin.com 
    forms.hsforms.com www.google.co.in www.google.co.ma www.google.co.nz www.google.co.za www.google.co.zw www.google.com.au www.google.com.br 
    www.google.com.gh www.google.com.my www.google.com.ng www.google.com.pe www.google.com.ph www.google.com.pr www.google.com.sg www.google.com.tr 
    www.google.com.ua www.google.com.vn www.google.cz www.google.dk www.google.es www.google.fr www.google.lk www.google.pt www.googletagmanager.com 
    log-papago.naver.com translate.google.com www.google.at www.google.be www.google.ch www.google.cl www.google.co.il www.google.co.ke www.google.com.ar 
    www.google.com.bd www.google.com.co www.google.com.kw www.google.com.mt www.google.com.mx www.google.com.np www.google.com.pk www.google.com.tw 
    www.google.com.uy www.google.fi www.google.ie www.google.is www.google.it www.google.jo www.google.nl www.google.no www.google.pl www.google.rs 
    www.google.se www.google.ae www.google.co.ao www.google.mu www.google.hu; font-src 'self' data: fonts.gstatic.com js.intercomcdn.com www.slant.co 
    storage.googleapis.com; connect-src 'self' api.segment.io api-iam.intercom.io forms.hubspot.com www.google-analytics.com heapanalytics.com 
    wss://nexus-websocket-a.intercom.io api.hubapi.com www.google.com; media-src js.intercomcdn.com; frame-src www.youtube.com intercom-sheets.com; 
    worker-src blob:; frame-ancestors 'self'; form-action calendly.com; manifest-src 'self'; report-uri https://courier.report-uri.com/r/d/csp/wizard;"

[[redirects]]
  from = "/favicon.ico"
  to = "/static/favicon/favicon.ico"
  status = 301

# marketing redirects

[[redirects]]
  from = "https://www.courier.com/sedaily"
  to = "https://www.courier.com/?utm_medium=podcast&utm_source=sedaily&utm_campaign=se-daily-podcast-q1"
  status = 301
  force = true

[[redirects]]
  from = "https://www.courier.com/hackabull"
  to = "https://app.courier.com/?utm_medium=hackathon&utm_source=hackbull-usf&utm_campaign=developer-relations"
  status = 301
  force = true

# other redirects

[[redirects]]
  from = "https://www.courier.com/careers"
  to = "https://jobs.lever.co/trycourier/"
  status = 301
  force = true
  
# site redirects to keep everything on the same domain

[[redirects]]
  from = "http://courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://www.courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true

[[redirects]]
  from = "https://courier.com"
  to = "https://www.courier.com"
  status = 301
  force = true

[[redirects]]
  from = "https://courier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "http://trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://trycourier.com/*"
  to = "https://www.courier.com/:splat"
  status = 301
  force = true
